# Generated by Django 5.0 on 2023-12-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passenger_capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
